### ISSUE TITLE
Is comfy-org associated with the core comfyui development team?

### ISSUE THREAD

**Issue by dmarx** [Comfy-Org/comfy-cli#1]
Most of ComfyUI has been developed by the github user [comfyanonymous](https://github.com/comfyanonymous). This user does not advertise their real name, but they do advertise that they are a Stability AI employee. I notice you don't have Stability AI listed on your LinkedIn. Is your Comfy-Org or this particular project in any way associated with the official mainline ComfyUI development team?

**Comment by yoland68** [comment]
Hahah, was really looking forward to post here back then but unfortunately had to wait for SD3 release.

Yes, we are the team to maintain and iterate on ComfyUI: https://comfy.org
