### ISSUE TITLE
[feature request] Bisect extensions command

### ISSUE THREAD

**Issue by melMass** [Comfy-Org/comfy-cli#103]
**Describe the solution you'd like**
I'm using a relatively similar concept to comfy-cli locally (written in nushell), we share a lot of commands but one that I'm starting to use more and more is a `bisect extensions` subcommand. Probably a niche one and more for devs than users but it really helps nailing down issues that might not have traceback, the most common I face is anything that modifies prototypes, since you wouldn't easily know where the issue was introduced

**Describe alternatives you've considered**
Just ignore it, it can be scripted around the cli tbh (mine just edit the suffix with `.disabled` and restarts the server)

**Additional context**
Long live comfy

**Comment by robinjhuang** [comment]
@melMass This was added https://github.com/Comfy-Org/comfy-cli/pull/126
Sorry for the late response. Feel free to enhance this feature if that suits your needs.

**Comment by melMass** [comment]
Awesome thanks for the heads up
