### ISSUE TITLE
Add mobile support

### ISSUE THREAD

**Issue by Mike-FreeAI** [Comfy-Org/comfy-cli#104]
**Describe the solution you'd like**
Please add mobile support

**Describe alternatives you've considered**
Using A1111

@DevApeAI go

**Comment by Mike-FreeAI** [comment]
@DevApeAI

**Comment by robinjhuang** [comment]
@Mike-FreeAI Do you need mobile support for ComfyUI? Or the cli specifically?

**Comment by yoland68** [comment]
This is a command line tool, there is no model support for this

**Comment by ltdrdata** [comment]
It seems you have likely found this repo after seeing Comfy-Org.
This is a sub-project repo of ComfyUI, and any UX-related issues for ComfyUI should still be requested in the [ComfyUI repo](https://github.com/comfyanonymous/ComfyUI).
And also check out [mcmonkeyprojects/SwarmUI](https://github.com/mcmonkeyprojects/SwarmUI), which uses ComfyUI as its backend.
