### ISSUE TITLE
[Feature Request] Install Specific Comfy Version Based On Commit

### ISSUE THREAD

**Issue by LucasMoskun** [Comfy-Org/comfy-cli#11]
It would be nice to be able to install a specific version instead of latest based on commit. Something like:

`comfy install --commit=<commit hash>`

seems like it would be pretty straightforward to add the the arg and then add a line here to checkout the commit before installing dependencies: https://github.com/Comfy-Org/comfy-cli/blob/6acc6bf90a4e6ec01da20e7c249cb00206cce902/comfy_cli/command/install.py#L49

**Comment by ltdrdata** [comment]
This is added.
