### ISSUE TITLE
Care to elaborate why would you EVER want any info about what user is doing ?

### ISSUE THREAD

**Issue by 3blackbar** [Comfy-Org/comfy-cli#132]
https://www.reddit.com/r/StableDiffusion/comments/1e65b21/watch_out_for_comfycli_on_comfyuimanager_repo_it/

We track analytics using Mixpanel to help us understand usage patterns and know where to prioritize our efforts.

Dood, seriously, nobody is buying this, just stop this shady shit ok ? Or would you mind sharing with us your social security and pass to your @mails ?

To what extent you spy, most ppl dgaf, so do i, id never install this shit.

**Comment by rafapimentel** [comment]
That's absolutely insane, beyond spying on nobodies and political dissidents are they ready to deal with litigation from companies with sensitive data using ComfyUI?? Let's say a company has internal loras for testing new characters for games, do you have the right to have to have data that could potentially be deanonimized and leak their IP before product launch? All of this "ask for consent" is useless in a company with hundreds of employees that are not software engineers using computers, one misclick and info leaks.
