### ISSUE TITLE
Using `comfy node init` with a LICENSE file creates an unusable pyproject.toml for Registry backend

### ISSUE THREAD

**Issue by teward** [Comfy-Org/comfy-cli#143]
**Describe the bug**
When using `comfy node init` in order to prepare a node for  uploading to the registry, the system attempts to refer to the LICENSE file.

Unfortunately, the Comfy Registry backend hard-fails on this with a 400 Bad Request.

**To Reproduce**
Steps to reproduce the behavior 

 - Create a node
 - Create a LICENSE file
 - Run `comfy node init` in that directory
 - `pyproject.toml` will be generated with a `license = { file = "LICENSE" }`
 - Attempt to upload the node fails with 400 Bad Request from the backend

**Expected behavior**

The Comfy-CLI `node init` would KNOW this is not valid and not generate that line in this way that would cause a failure.

**Comment by robinjhuang** [comment]
I believe this is resolved now.
