### ISSUE TITLE
wstimeout

### ISSUE THREAD

**Issue by mjygit** [Comfy-Org/comfy-cli#152]
/usr/local/lib/python3.11/site-packages/comfy_cli/command/run.py:176 in │
│ watch_execution │
│ │
│ 173 │ def watch_execution(self): │
│ 174 │ │ self.ws.settimeout(30) │
│ 175 │ │ while True: │
│ ❱ 176 │ │ │ message = self.ws.recv() │

When handling larger images, this part results in a web socket timeout, preventing further execution.
Is it possible to dynamically configure the timeout duration as a parameter for the comfy run command?

**Comment by yoland68** [comment]
You can set wstimeout with the timeout flag when doing run

https://github.com/Comfy-Org/comfy-cli/blob/41e98b5009267946ff8ade6acafd3266cb50af8d/comfy_cli/cmdline.py#L398

`comfy run --workflow ~/default.json --timeout 1`
