### ISSUE TITLE
How to run a workflow programmatically just using comfy, without starting the comfyui server?

### ISSUE THREAD

**Issue by PeterTF656** [Comfy-Org/comfy-cli#155]
Hey guys, I'm looking for a command that can run a workflow programmatically just using comfy, without starting the comfyui server. It was mentioned [here in this issue](https://github.com/comfyanonymous/ComfyUI/issues/737)

**Comment by SayanoAI** [comment]
this would be extremely useful for cloud serverless applications!

**Comment by robinjhuang** [comment]
You can run a workflow like this: 

```
comfy launch --background
comfy run --workflow /path/to/api_workflow.json
```

You MUST start the comfy server to run anything. However you don't need to open the UI to run a workflow.

**Comment by q351941406** [comment]
How can I check the progress of the task?

**Comment by robinjhuang** [comment]
Not supported yet!

**Comment by q351941406** [comment]
@robinjhuang You can add this feature because many tasks are very time-consuming, and we need to know the progress.

**Comment by robinjhuang** [comment]
We're a bit swamped at the moment, but can you write a PR? Probably the easiest thing is to stream the STDOUT of the comfy server to the cli STDOUT during the workflow run.

**Comment by q351941406** [comment]
I'm not good enough
