### ISSUE TITLE
Missing HUGGINGFACE_API_TOKEN_KEY

### ISSUE THREAD

**Issue by schananas** [Comfy-Org/comfy-cli#174]
Currently, its only possible to provide CIVITAI_API_TOKEN_KEY when downloading models from CivitAI.

But if we are downloading from HuggingFace, there is no such option, its not possible to download private models.

Solution: provide HF_API_TOKEN_KEY when downloading from HuggingFace

**Comment by rougsig** [comment]
Want too

**Comment by yoland68** [comment]
Added option in branch
