### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by LucasMoskun** [Comfy-Org/comfy-cli#2]
Hello, I understand I am be a little early to the party, but really excited for this :-)

I've just tried to install comfy-cli on windows following the steps in the readme, but have ran into some issues

python - 3.12.3
windows 11

```
mkdir comfy-cli
cd comfy-cli
python -m venv venv . 
venv\Scripts\Activate
python -m pip install comfy-cli
comfy install
```

results in:
```
 C:\comfy-cli> comfy install
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\comfy-cli\venv\Scripts\comfy.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'comfy'
```

**Comment by ltdrdata** [comment]
Currently in development, the latest build is not deployed on PyPI. If you want to try the latest version with this issue patched, you need to clone it from git and install it from your local repo.

Activate your `venv` and run the following commands to install:
```
git clone https://github.com/Comfy-Org/comfy-cli
cd comfy-cli
pip install .
comfy install
```

**Comment by LucasMoskun** [comment]
ty :-)

That seemed to work well, however, now, when I run `comfy launch` I get the following error
```
(venv) PS C:\ComfyUI> comfy launch

Launch ComfyUI from current repo: C:\ComfyUI

Traceback (most recent call last):
 File "C:\ComfyUI\main.py", line 73, in <module>
  import comfy.utils
 File "C:\ComfyUI\comfy\utils.py", line 1, in <module>
  import torch
ModuleNotFoundError: No module named 'torch'
```
So, per the comfyUI readme I tried to install torch specifically for nvidia 
```
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121`
```
and this allowed me to atleast run the comfy-cli installed version of comfyUI using `python -m main.py` (still in the venv I installed comfy-cli with)

however `comfy launch` still throws the same module error. 

Also maybe worth noting I am not finding a generated _comfy.yaml_. 

(I also tried `comfy install` inside an existing repo and no _comfy.yaml_ was generated either)

**Comment by ltdrdata** [comment]
This is fixed now.

**Comment by LucasMoskun** [comment]
> This is fixed now.

Awesome 😎 

Is the generation of the `comfy.yaml` and the ability to manage dependencies not implemented on main yet?

**Comment by ltdrdata** [comment]
> > This is fixed now.
> 
> Awesome 😎
> 
> Is the generation of the `comfy.yaml` and the ability to manage dependencies not implemented on main yet?

That feature has not been implemented yet.

**Comment by LucasMoskun** [comment]
Right on, thanks again!
