### ISSUE TITLE
Any way to use the Command Line Arguments?

### ISSUE THREAD

**Issue by JaypTookMyJayp** [Comfy-Org/comfy-cli#203]
I found out that ComfyUI let us use multiple command line args (https://www.reddit.com/r/comfyui/comments/15jxydu/comfyui_command_line_arguments_informational/)

but I found out that the below command doesn't work
"comfy launch --background --cuda-malloc --use-pytorch-cross-attention --highvram"

if there is any way to do so, please let me know!

**Comment by ltdrdata** [comment]
> "comfy launch --background --cuda-malloc --use-pytorch-cross-attention --highvram"

use `--` to pass extra args to ComfyUI.

`comfy launch -- --background --cuda-malloc --use-pytorch-cross-attention --highvram`
