### ISSUE TITLE
specify commit hash not work

### ISSUE THREAD

**Issue by sko00o** [Comfy-Org/comfy-cli#212]
**Describe the bug**

**comfy-cli:  v1.3.1**

I want to install specify version of ComfyUI using following command:

```sh
COMFYUI_COMMIT=8a5281006f178f9aa0e8cbd4fc29e2f3c119d2e2
comfy install --version nightly --commit ${COMFYUI_COMMIT}
```

But I still got the latest commit.

**To Reproduce**
Steps to reproduce the behavior 

```sh
cd /tmp
COMFYUI_COMMIT=8a5281006f178f9aa0e8cbd4fc29e2f3c119d2e2
comfy --skip-prompt --here install --cpu --version nightly --commit ${COMFYUI_COMMIT}

# view current commit hash
cd ./ComfyUI && git rev-parse HEAD
```

Terminal output:

```
# ... omit install output ...
41886af138939719b86f30bacbafc76a142d89de
```

**Expected behavior**

I need `--commit` option works.

**Nice to have**
- [x] Terminal output
- [ ] Screenshots

**Additional context**

**Comment by sko00o** [comment]
I think this bug comes from the callback function `validate_commit_and_version` didn't return value. 

https://github.com/Comfy-Org/comfy-cli/blob/b2ba7d0b3c8b2bfc276a6e1ff9bb4f1b0561cd7e/comfy_cli/cmdline.py#L140-L146

 I fixed it and send a PR (https://github.com/Comfy-Org/comfy-cli/pull/213).

**Comment by robinjhuang** [comment]
Thank you @sko00o! Merged and will make a new version.
