### ISSUE TITLE
Globally installed comfy-cli should respect local venv/conda env

### ISSUE THREAD

**Issue by yoland68** [Comfy-Org/comfy-cli#75]
When comfy command is installed in global context but triggered in venv or conda env, it should use python and pip from that environment

**Comment by robinjhuang** [comment]
I tried it again with the latest version `v1.0.33` and it works now. 

Steps to reproduce: 
1. Install comfy globally (not inside any venv). 
2. Activate a venv and install dependencies.
3. `comfy launch`. It works and uses the venv's python.

**Comment by daviddavid** [comment]
This is broken again. No matter if I use a conda env or activate a venv, the globally installed python executable is used.

I think it's due to this PR: https://github.com/Comfy-Org/comfy-cli/pull/158 @telamonian
