### ISSUE TITLE
Update a node's icon field from pyproject.toml when publishing

### ISSUE THREAD

**Issue by robinjhuang** [Comfy-Org/comfy-cli#88]
Currently the `comfy node publish` command doesn't send the icon field to the registry API. 

Requirements:
- Read icon field from pyproject.toml
- Send field contents to API

Tips:
Modify the `publish_node_version` function to take a icon field. You can add a icon field to the `PyProjectConfig` dataclass. [Code](https://github.com/Comfy-Org/comfy-cli/blob/main/comfy_cli/registry/api.py)
Update the `extract_node_configuration` function to return the icon field from pyproject.toml. [Code](https://github.com/Comfy-Org/comfy-cli/blob/main/comfy_cli/registry/config_parser.py)

**Comment by robinjhuang** [comment]
Anyone want to help with this one?

**Comment by ryphon** [comment]
Also, Icon was already in the ComfyConfig (and config parser), it just wasn't being passed via the requests post body.
