### ISSUE TITLE
Error Numpy v2

### ISSUE THREAD

**Issue by Nestorchik** [Comfy-Org/comfy-cli#97]
ComfyUI Installed by:   comfy install  (comfy_cli)

![000](https://github.com/Comfy-Org/comfy-cli/assets/74113797/95123376-379d-43ed-91a8-17ec704d1514)

Help this operation:
python -m pip uninstall numpy -y
python pip install numpy==1.26.4

**Comment by ltdrdata** [comment]
Actually, this is not an issue with `comfy-cli`. 

The recently updated numpy is causing compatibility errors with other packages. This problem is not only affecting comfy-cli but also all users who have recently installed ComfyUI.

**Comment by robinjhuang** [comment]
https://github.com/comfyanonymous/ComfyUI/issues/3794
Following the issue in ComfyUI.
